# Generated by Django 4.1 on 2023-02-12 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='bundle_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=256)),
                ('payment_number', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('payment_description', models.CharField(blank=True, max_length=500, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('payment_visited', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
