# Generated by Django 4.1 on 2023-06-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0002_alter_isharebundletransaction_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_visited',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
