# Generated by Django 4.1 on 2023-06-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0003_remove_payment_payment_visited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
