# Generated by Django 4.2.5 on 2023-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0006_isharebundleprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IshareBundlePrice',
            new_name='MTNBundlePrice',
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
