# Generated by Django 4.2.4 on 2023-11-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0008_site_ishare_status_alter_payment_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtnbundletransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('Flexi', 'Flexi'), ('Normal', 'Normal')], default='Normal', max_length=200, null=True),
        ),
    ]
