# Generated by Django 4.2.4 on 2023-11-10 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0011_notificationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmessage',
            name='title',
        ),
    ]
