# Generated by Django 4.2.4 on 2023-11-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestPayApp', '0013_notificationmessage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmessage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
